{{- if .Values.serviceAccount.create }}
{{- $annotations := merge (dict) (.Values.serviceAccount.annotations | default dict) (fromYaml (include "locust-load-tester.annotations" .)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "locust-load-tester.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "locust-load-tester.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
